<?php
/**
 * Injects the floating WPPilot button and sidebar into WP Admin.
 *
 * @package WPPilot
 */

defined( 'ABSPATH' ) || exit;

class WPPilot_Admin {

	public function init(): void {
		add_action( 'admin_enqueue_scripts', [ $this, 'enqueue_assets' ] );
		add_action( 'admin_footer',          [ $this, 'render_container' ] );
	}

	private function should_load(): bool {
		if ( ! current_user_can( 'manage_woocommerce' ) ) {
			return false;
		}

		$screen = get_current_screen();
		if ( ! $screen ) {
			return true;
		}

		// Don't load on plugin/theme management pages — avoids JS conflicts with
		// tools like Plugin Check that run their own scripts there.
		$excluded = [ 'plugins', 'plugin-install', 'plugin-editor', 'themes', 'theme-editor', 'update-core', 'tools_page_plugin-check' ];

		if ( in_array( $screen->id, $excluded, true ) ) {
			return false;
		}

		// Allow third-party code to control loading per screen.
		return (bool) apply_filters( 'wppilot_load_on_screen', true, $screen );
	}

	public function enqueue_assets(): void {
		if ( ! $this->should_load() ) {
			return;
		}

		$build_dir  = WPPILOT_DIR . 'build/';
		$asset_file = $build_dir . 'index.asset.php';

		// Vite/wp-scripts generates an asset manifest; fall back gracefully.
		// Use filemtime so the browser re-fetches whenever the build changes.
		// wp-element must be listed so WordPress loads React before our script.
		// The asset manifest (generated by @wordpress/scripts) would include this
		// automatically; since we use Vite we declare it explicitly in the fallback.
		$asset = file_exists( $asset_file )
			? require $asset_file
			: [ 'dependencies' => [ 'wp-element' ], 'version' => filemtime( $build_dir . 'index.js' ) ?: WPPILOT_VERSION ];

		wp_enqueue_script(
			'wppilot-ui',
			WPPILOT_URL . 'build/index.js',
			$asset['dependencies'],
			$asset['version'],
			true
		);

		wp_localize_script(
			'wppilot-ui',
			'wppilotData',
			[
				'apiUrl'          => esc_url_raw( rest_url( 'wppilot/v1' ) ),
				'wpApiUrl'        => esc_url_raw( rest_url( 'wp/v2' ) ),
				'nonce'           => wp_create_nonce( 'wp_rest' ),
				'hasBYOKey'       => $this->ai_provider_ready(),
				'siteUrl'         => esc_url_raw( home_url() ),
				'i18n'            => [
					'placeholder'    => __( 'Ask StoreHand AI Product Manager anything about your products…', 'storehand-ai-product-manager-for-woocommerce' ),
					'send'           => __( 'Send', 'storehand-ai-product-manager-for-woocommerce' ),
					'thinking'       => __( 'StoreHand AI Product Manager is thinking…', 'storehand-ai-product-manager-for-woocommerce' ),
					'toolRunning'    => __( 'Running action…', 'storehand-ai-product-manager-for-woocommerce' ),
				],
			]
		);
	}

	private function ai_provider_ready(): bool {
		return function_exists( 'wp_ai_client_prompt' );
	}

	public function render_container(): void {
		if ( ! $this->should_load() ) {
			return;
		}
		// phpcs:disable WordPress.Security.EscapeOutput.OutputNotEscaped
		?>
		<div id="wppilot-root"></div>
		<?php
		// phpcs:enable
	}
}
